# Generated by Django 5.1.5 on 2025-01-25 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=0.0, null=True)),
                ('humidity', models.FloatField(blank=True, default=0.0, null=True)),
                ('methane', models.FloatField(blank=True, default=0.0, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
